### ISSUE TITLE
About the pretrained model

### ISSUE THREAD

**Issue by yuzheyyyy** [ptran1203/pytorch-animeGAN#1]
I would like to know whether you have released the pretrained model for inference?

**Comment by ptran1203** [comment]
Yes, I have released Hayao's weight [here](https://github.com/ptran1203/pytorch-animeGAN/releases/download/v1.0/generator_hayao.pth)

To load from code
```python3
from inference import Transformer
transformer = Transformer('hayao')
```

you can check my [example notebook](https://github.com/ptran1203/pytorch-animeGAN/blob/master/notebooks/animeGAN_inference.ipynb)

**Comment by dongyun-kim-arch** [comment]
Hi patron,
Could you also share the parameter values used in training? I am trying to retrieve the same results like original paper, but not easy to reproduce it.

**Comment by Leanne-z** [comment]
Hi, could you share other weight parameters? Like Kimetsu or Summer War
