### ISSUE TITLE
What is the exact input shape of model?

### ISSUE THREAD

**Issue by NicolasLaube** [ptran1203/pytorch-animeGAN#14]
I integrated/adapted your code to my pipeline. However, when I train the model, I get some strange results. I think that it comes from the input matrices of cartoons (edged/gray/normal)...
![image](https://user-images.githubusercontent.com/45005101/161308648-83f8721f-3d13-4e88-9338-f027b5fe364c.png)

What are the expected cartoon and picture input shapes/order of channels ?

**Comment by ptran1203** [comment]
- Training images are read by cv2, default color space is RGB, but I reversed it to BGR.
- There is no particular input shape, it can be any, my dataset use 256x256 and you can inference on any shape
- What dataset do you use in training?

**Comment by NicolasLaube** [comment]
Thank you for your quick response ! We are training the model on a custom cartoons dataset (more Pixar like images).

**Comment by NicolasLaube** [comment]
I still have a last question, is the shape (3, im_size_height, im_size_width) ?

**Comment by ptran1203** [comment]
> I still have a last question, is the shape (3, im_size_height, im_size_width) ?

Yes, in PyTorch channel first order is default

If you train on custom data, it's hard to say but you may need to tune some params (e.g loss weight, ...)

**Comment by NicolasLaube** [comment]
Ok, thank you !
