### ISSUE TITLE
   Error in Video transform self.proc.stdin.write(img_array.tobytes()) ValueError: write to closed file

### ISSUE THREAD

**Issue by Louis24** [ptran1203/pytorch-animeGAN#16]
def video():
    os.system("python inference_video.py "
              "--checkpoint generator_hayao.pth "
              "--src C:/Zero/Python/AnimeGAN/test.mp4 "
              "--dest res.mp4 "
              "--batch 2")

When I run this, got the error above, I have print the val of img it is correct I think sth wrong with the writer

**Comment by ptran1203** [comment]
Could you show the error more specifically? 
I don't see the error message, I guess it's the command you have run.
