### ISSUE TITLE
Very good job

### ISSUE THREAD

**Issue by Apathetically** [ptran1203/pytorch-animeGAN#2]
The code can indeed run and the effect is very good. I don’t understand why there are so few people star this project. I hope more and more people can pay attention to this.

**Comment by ptran1203** [comment]
thanks for your compliment! I really hope that too :D

**Comment by muzzol** [comment]
Is nvidia card mandatory?
I have some powerful machines with other gpus.

**Comment by ptran1203** [comment]
@muzzol I am not sure, Cuda is mostly working with Nvidia GPUs. You can use colab instead

**Comment by muzzol** [comment]
> @muzzol I am not sure, Cuda is mostly working with Nvidia GPUs. You can use colab instead

yeah, I'll try that. Is just that I want to use big files and I don't have them on GDrive.
