### ISSUE TITLE
Unzip anime-gan.zip failed

### ISSUE THREAD

**Issue by zhanglonghao1992** [ptran1203/pytorch-animeGAN#4]
Would you mind sharing your training dataset? The dataset I downloaded with ```wget -O anime-gan.zip https://github.com/ptran1203/pytorch-animeGAN/releases/download/v1.0/dataset_v1.zip``` cannot be decompressed.
>unzip:  cannot find zipfile directory in one of anime-gan.zip or        anime-gan.zip.zip, and cannot find anime-gan.zip.ZIP, period.

**Comment by ptran1203** [comment]
The error says that `unzip` can't find the file you just downloaded. Could you check again your file path?

**Comment by zhanglonghao1992** [comment]
> The error says that `unzip` can't find the file you just downloaded. Could you check again your file path?

I downloaded two copies on the server and locally, both of which reported errors

**Comment by ptran1203** [comment]
Please try with `unzip anime-gan.zip`, and make sure `ls` command shows `anime-gan.zip` in your current directory

**Comment by zhanglonghao1992** [comment]
> Please try with `unzip anime-gan.zip`, and make sure `ls` command shows `anime-gan.zip` in your current directory

Dude, I konw how to unzip...

**Comment by ptran1203** [comment]
Oh sorry about that :)), I can confirm that I can unzip with the downloaded file on my computer

![image](https://user-images.githubusercontent.com/36766404/141718573-81ef6fa4-f059-4455-989e-65405fec1739.png)

**Comment by zhanglonghao1992** [comment]
> Oh sorry about that :)), I can confirm that I can unzip with the downloaded file on my computer
> 
> ![image](https://user-images.githubusercontent.com/36766404/141718573-81ef6fa4-f059-4455-989e-65405fec1739.png)

：） Would you mind uploading one of the sub-dataset (like Hayao or Kimetse) to Google Drive or Baidu Netdisk~

**Comment by ptran1203** [comment]
Here https://drive.google.com/file/d/1HsT05rb0WYNB-twFr4voFAYWvmFBDB4o/view?usp=sharing

**Comment by zhanglonghao1992** [comment]
> Here https://drive.google.com/file/d/1HsT05rb0WYNB-twFr4voFAYWvmFBDB4o/view?usp=sharing

Thanks~

**Comment by zbzzz** [comment]
Would you mind uploading one of these subdatasets (Hayao) to Google Drive or Baidu Drive
